#!/bin/bash

BASE=./pages
OUT=out
TARGET=../$OUT

mkdir -p $OUT

cd $BASE
LIST=`ls | grep '.*\.man' | sort`

TABLE=''
for f in $LIST; do
    echo "prerocessing $f..."
    cat $f | awk '
        /#include/ { system("cat "substr($0, 11)); }
        !/#include/ { print $0 }
    ' > $TARGET/$f
    # cat $TARGET/$f
done
